### ISSUE TITLE
Final manual verification with a few IDEs

### ISSUE THREAD

**Issue by rluce** [Gurobi/gurobipy-stubs#10]
Before pushing out the 2.0 release I'd like to confirm that "everything looks good" in VS Code and PyCharm.

**Comment by simonbowly** [comment]
Looks good in vscode:

![image](https://user-images.githubusercontent.com/7454632/201217511-2739e713-da95-42e2-807f-56c0d8ef592f.png)

![image](https://user-images.githubusercontent.com/7454632/201217599-80e9990f-2711-46a0-b186-68c8b5982951.png)

![image](https://user-images.githubusercontent.com/7454632/201217771-36188a8a-5660-4aa1-b058-79f3f223635f.png)

![image](https://user-images.githubusercontent.com/7454632/201217875-11f4fcb9-2795-4ba6-8148-9a515bbf9afc.png)

![image](https://user-images.githubusercontent.com/7454632/201218385-2ac71f82-8ca9-4e71-bb2a-7f4b691fcef9.png)

**Comment by rluce** [comment]
Looking good, closing.
