### ISSUE TITLE
Add stubs for gp.Env environment variables like ClientEnv, CloudEnv

### ISSUE THREAD

**Issue by valentincalomme** [Gurobi/gurobipy-stubs#12]
In my project, mypy was complaining at the following code:

```py
import gurobipy as gp

env = gp.Env.ClientEnv(
        logfilename="", computeServer="my_gurobi_server", password="my_password"
    )
```

Raising the following error: `"Type[Env]" has no attribute "ClientEnv"  [attr-defined]mypy(error)`

And when investigating, I realized that the stubs for `Env` indeed do not include any attributes, only methods. It would be nice to modify the stubs to avoid needing to use `type:ignore`

**Comment by simonbowly** [comment]
`gp.Env.ClientEnv` and `gp.Env.CloudEnv` were deprecated in Gurobi 9.5, and [removed in Gurobi 10.0](https://www.gurobi.com/documentation/10.0/refman/detailed_release_notes_10.html). You should instead use `gp.Env(params=)` to set compute server or instant cloud connection parameters as specified [in the documentation](https://www.gurobi.com/documentation/10.0/refman/py_env2.html#pythonmethod:Env).
